# Generated by Django 4.2.7 on 2026-07-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(max_length=100, unique=True)),
                ('license_name', models.CharField(max_length=200)),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('block', 'Block'), ('warn', 'Warn')], default='warn', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'License policies',
            },
        ),
        migrations.AddField(
            model_name='scan',
            name='license_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='scan',
            name='license_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='scan',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10),
        ),
    ]
